### PR TITLE
Use empty username when username is not present in snapshot.

### PR DESCRIPTION
**Pull request by Enrico204**
This MR is fixing a crash when the snapshot has no username field in JSON. The missing username is replaced with a space.

(I have snapshots of my smartphone where the `username` key is missing)

### CODE REVIEW

**Comment by ngosang** [comment]
Thank you. Could you check in restic cli if there is something in the user column. I'm ok with an empty value but maybe "unknown" or some value is more useful.

**Comment by Enrico204** [comment]
The JSON produced by the `restic snapshots --json` has no "username" field for my smartphone snapshots, while a snapshot from a Linux host correctly contains that field.

Without the `--json` flag, there is no "username" column for both. I don't know if there is any flag to show that column.

**Comment by ngosang** [comment]
Thank you. I will merge it and publish a new release this weekend.

**Review by ngosang — APPROVED** [review]

**Comment by ngosang** [comment]
https://github.com/ngosang/restic-exporter/releases/tag/1.2.0

**Pull request merged**
